# -*- coding: utf-8 -*-
"""Brain_Tumor_VGG16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m0eTOusUUVexOjTks0ZOSJLg4eTSjMU3

# 🧠 Brain Tumor Detection using VGG16 Transfer Learning
**Model:** VGG16 | **Classes:** Glioma, Meningioma, No Tumor, Pituitary

> ⚠️ Enable GPU: Runtime → Change runtime type → T4 GPU
"""

# ── STEP 1: DOWNLOAD DATASET ────────────────────────────────
import kagglehub

path = kagglehub.dataset_download("masoudnickparvar/brain-tumor-mri-dataset")
print("Path to dataset files:", path)

# ── STEP 2: IMPORTS ─────────────────────────────────────────
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import layers, callbacks
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report, confusion_matrix

print("✅ All imports done!")
print("TensorFlow version:", tf.__version__)

# ── STEP 3: PATHS & SETTINGS ────────────────────────────────
TRAIN_PATH  = os.path.join(path, "Training")
TEST_PATH   = os.path.join(path, "Testing")
IMG_SIZE    = (224, 224)
BATCH_SIZE  = 32
NUM_CLASSES = 4

print("Train Path:", TRAIN_PATH)
print("Test Path: ", TEST_PATH)

# ── STEP 4: CHECK CLASS DISTRIBUTION ───────────────────────
print("\n📊 Class Distribution:\n")
for split, p in [("Training", TRAIN_PATH), ("Testing", TEST_PATH)]:
    print(f"  {split}:")
    for cls in sorted(os.listdir(p)):
        cls_path = os.path.join(p, cls)
        if os.path.isdir(cls_path):
            count = len([
                f for f in os.listdir(cls_path)
                if f.lower().endswith(('.png', '.jpg', '.jpeg'))
            ])
            print(f"    {cls:15s} → {count} images")

# ── STEP 5: DATA AUGMENTATION ───────────────────────────────
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
    layers.RandomBrightness(0.1),
])

print("✅ Augmentation pipeline ready!")

# ── STEP 6: LOAD DATASET ────────────────────────────────────
train_ds = tf.keras.utils.image_dataset_from_directory(
    TRAIN_PATH,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical'
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    TRAIN_PATH,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical'
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    TEST_PATH,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='categorical',
    shuffle=False
)

class_names = train_ds.class_names
print("\n✅ Classes:", class_names)

# ── STEP 7: PERFORMANCE OPTIMIZATION ────────────────────────
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds   = val_ds.cache().prefetch(buffer_size=AUTOTUNE)
test_ds  = test_ds.cache().prefetch(buffer_size=AUTOTUNE)

print("✅ Performance optimization done!")

# ── STEP 8: HANDLE CLASS IMBALANCE ──────────────────────────
# Glioma=1321, Meningioma=1339, NoTumor=1595, Pituitary=1457
total     = 5712
n_glioma  = 1321
n_menin   = 1339
n_notumor = 1595
n_pitu    = 1457

def cw(n): return (1 / n) * (total / 2)

class_weight = {
    0: cw(n_glioma),
    1: cw(n_menin),
    2: cw(n_notumor),
    3: cw(n_pitu)
}
print("⚖️  Class Weights:", class_weight)

# ── STEP 9: BUILD VGG16 MODEL ───────────────────────────────
base_model = VGG16(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)
base_model.trainable = False  # Phase 1 ma freeze

inputs  = tf.keras.Input(shape=(224, 224, 3))
x       = data_augmentation(inputs)
x       = tf.keras.applications.vgg16.preprocess_input(x)
x       = base_model(x, training=False)
x       = layers.GlobalAveragePooling2D()(x)
x       = layers.Dense(256, activation='relu')(x)
x       = layers.Dropout(0.5)(x)
outputs = layers.Dense(NUM_CLASSES, activation='softmax')(x)

model = Model(inputs, outputs)
model.summary()

# ── STEP 10: COMPILE WITH CALLBACKS ─────────────────────────
model.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

early_stop = callbacks.EarlyStopping(
    monitor='val_loss', patience=5,
    restore_best_weights=True, verbose=1
)
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor='val_loss', factor=0.3,
    patience=3, verbose=1
)
checkpoint = callbacks.ModelCheckpoint(
    'best_vgg16_phase1.keras',
    save_best_only=True, verbose=1
)

print("✅ Model compiled!")

# ── STEP 11: TRAIN — PHASE 1 (frozen base) ──────────────────
print("\n🚀 Phase 1 Training — Head only...\n")

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15,
    class_weight=class_weight,
    callbacks=[early_stop, reduce_lr, checkpoint]
)

# ── STEP 12: FINE TUNING — PHASE 2 (unfreeze top layers) ────
print("\n🔧 Phase 2 — Fine Tuning...\n")
base_model.trainable = True
fine_tune_at = 15  # First 15 layers freeze rakho

for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

model.compile(
    optimizer=Adam(learning_rate=1e-5),  # Very low LR
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

checkpoint2 = callbacks.ModelCheckpoint(
    'best_vgg16_finetuned.keras',
    save_best_only=True, verbose=1
)

history_fine = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    class_weight=class_weight,
    callbacks=[early_stop, reduce_lr, checkpoint2]
)

# ── STEP 13: PLOT RESULTS ────────────────────────────────────
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'],          label='Train Acc P1')
plt.plot(history.history['val_accuracy'],      label='Val Acc P1')
plt.plot(history_fine.history['accuracy'],     label='Train Acc P2')
plt.plot(history_fine.history['val_accuracy'], label='Val Acc P2')
plt.title('Accuracy'); plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'],          label='Train Loss P1')
plt.plot(history.history['val_loss'],      label='Val Loss P1')
plt.plot(history_fine.history['loss'],     label='Train Loss P2')
plt.plot(history_fine.history['val_loss'], label='Val Loss P2')
plt.title('Loss'); plt.legend()

plt.tight_layout()
plt.savefig('training_results.png', dpi=150)
plt.show()

# ── Confusion Matrix ──────────────────────────────────────────
print("\n📋 Evaluating on Test Set...\n")
y_pred, y_true = [], []

for images, labels in test_ds:
    preds = model.predict(images, verbose=0)
    y_pred.extend(np.argmax(preds, axis=1))
    y_true.extend(np.argmax(labels.numpy(), axis=1))

print(classification_report(y_true, y_pred, target_names=class_names))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150)
plt.show()

# ── STEP 14: SAVE MODEL ──────────────────────────────────────
model.save("brain_tumor_vgg16_final.keras")
print("\n✅ Model saved locally!")

from google.colab import drive
import shutil

drive.mount('/content/drive')
shutil.copy(
    'brain_tumor_vgg16_final.keras',
    '/content/drive/MyDrive/brain_tumor_vgg16_final.keras'
)
print("✅ Model saved to Google Drive!")